### ISSUE TITLE
Qustions

### ISSUE THREAD

**Issue by ffnull** [lasselukkari/AirMonitor#1] opened 2019-09-01 09:29 UTC
Hello.Great code! i modify it to work with sht1x. Works great. Can you add more comments to code and explain how to add enother plot? i whant add mesure of TVOC sensor

**Comment by ffnull** [comment] 2019-09-01 18:06
By the way. Found BUG. IF its work more then 5-7 hours its stuck and needs reboot

**Comment by lasselukkari** [comment] 2019-09-03 15:27
Hello!

Adding a new plot is fairly easy.

For the front end add the required changes here: https://github.com/lasselukkari/AirMonitor/blob/master/src/App.js#L8-L19
Note that the the parameter name in `state.current` and `state.history` needs to be the same as the `panel.name` but in lowercase (`CO2` => `co2`, `Temperature` => `temperature` etc.).

In your modifications to the [Arduino backend](https://github.com/lasselukkari/AirMonitor/blob/master/AirMonitorServer/AirMonitorServer.ino) use the same lowercase name everywhere.

Most likely the bug is caused by some instability in the esp32 arduino core. The recent 1.0.3-rc2 version seems to be the first somewhat working version since 1.0.1 that was introduced last spring. To see what is going on set the core debug level to verbose and monitor the serial port for debug logs. Also the library dependencies vendored with the project are outdated.

I'm planning to revisit this project in the near future. The next version will use an sd card to store the measurements and possibly a RTC to get proper timestamps for the logs.

**Comment by ffnull** [comment] 2019-09-03 15:34
Great! Thanks for responding so quickly. Im using esp32 m5stack with latest
arduino core

вт, 3 сент. 2019 г. в 18:27, Lasse Lukkari <notifications@github.com>:

**Comment by lasselukkari** [comment] 2019-09-21 18:36
Hi! The changes I was talking about were now merged: https://github.com/lasselukkari/AirMonitor/pull/2

**Closed by lasselukkari** 2019-09-21 18:36 UTC
